# Generated by Django 4.1.7 on 2023-03-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registroStreaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='plataforma',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
